### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by johnjelinek** [GeertJohan/go.rice#57]
After running `rice embed-go` I get 33M `*.rice-box.go` file. When I run `go build` after that, I can't get it to build because RAM shoots up to more than 14.5GB. I've tried increasing my swap, but it keeps maxing it out. Any idea what's happening?

**Comment by johnjelinek** [comment]
Also, build time is extremely high -- I've maxed out around an hour and 15 minutes before it dies from max RAM+swap usage

**Comment by johnjelinek** [comment]
Example stack trace:

```
fatal error: runtime: failed to commit pages

runtime stack:
runtime.SysUsed(0xc0821e8000, 0x2000)
        c:/go/src/runtime/mem_windows.c:75 +0x79
runtime.MHeap_Alloc(0xab6780, 0x1, 0x10000000023, 0x4785f0)
        c:/go/src/runtime/mheap.c:240 +0x7b
runtime.MCentral_CacheSpan(0xabf818, 0x484d73)
        c:/go/src/runtime/mcentral.c:85 +0x16e
runtime.MCache_Refill(0x180000, 0xc000000023, 0xc08201dd48)
        c:/go/src/runtime/mcache.c:90 +0xae

goroutine 11 [running]:
runtime.switchtoM()
        c:/go/src/runtime/asm_amd64.s:198 fp=0xc08201dc70 sp=0xc08201dc68
runtime.mallocgc(0x600, 0x75bc00, 0xc000000001, 0x200)
        c:/go/src/runtime/malloc.go:178 +0x850 fp=0xc08201dd20 sp=0xc08201dc70
runtime.newarray(0x75bc00, 0x600, 0xc082000e00)
        c:/go/src/runtime/malloc.go:365 +0xc8 fp=0xc08201dd58 sp=0xc08201dd20
runtime.makeslice(0x74da00, 0x600, 0x600, 0x0, 0x0, 0x0)
        c:/go/src/runtime/slice.go:32 +0x163 fp=0xc08201dda0 sp=0xc08201dd58
bytes.makeSlice(0x600, 0x0, 0x0, 0x0)
        c:/go/src/bytes/buffer.go:191 +0x71 fp=0xc08201ddf0 sp=0xc08201dda0
bytes.(*Buffer).ReadFrom(0xc0820ba230, 0x192a80, 0xc082044660, 0x56, 0x0, 0x0)
        c:/go/src/bytes/buffer.go:163 +0xe1 fp=0xc08201de88 sp=0xc08201ddf0
io.Copy(0x198168, 0xc0820ba230, 0x192a80, 0xc082044660, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:358 +0x144 fp=0xc08201df40 sp=0xc08201de88
os/exec.func┬╖003(0x0, 0x0)
        c:/go/src/os/exec/exec.go:221 +0x84 fp=0xc08201dfa0 sp=0xc08201df40
os/exec.func┬╖004(0xc08219a700)
        c:/go/src/os/exec/exec.go:328 +0x34 fp=0xc08201dfd8 sp=0xc08201dfa0
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc08201dfe0 sp=0xc08201dfd8
created by os/exec.(*Cmd).Start
        c:/go/src/os/exec/exec.go:329 +0xcad

goroutine 1 [semacquire, 129 minutes]:
sync.(*WaitGroup).Wait(0xc08219a060)
        c:/go/src/sync/waitgroup.go:132 +0x170
main.(*builder).do(0xc08205eee0, 0xc0820245b0)
        c:/go/src/cmd/go/build.go:768 +0x5c6
main.runBuild(0xa9d5e0, 0xc082003e80, 0x0, 0x0)
        c:/go/src/cmd/go/build.go:303 +0x4ca
main.main()
        c:/go/src/cmd/go/main.go:163 +0x60f

goroutine 5 [syscall, 132 minutes]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init┬╖1
        c:/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 7 [syscall, 129 minutes, locked to thread]:
syscall.WaitForSingleObject(0x180, 0xc0ffffffff, 0x4a5601, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:689 +0x76
os.(*Process).wait(0xc08219acc0, 0x0, 0x0, 0x0)
        c:/go/src/os/exec_windows.go:16 +0x92
os.(*Process).Wait(0xc08219acc0, 0xc08205d7a0, 0x0, 0x0)
        c:/go/src/os/doc.go:45 +0x41
os/exec.(*Cmd).Wait(0xc0821ab7c0, 0x0, 0x0)
        c:/go/src/os/exec/exec.go:364 +0x243
os/exec.(*Cmd).Run(0xc0821ab7c0, 0x0, 0x0)
        c:/go/src/os/exec/exec.go:246 +0x78
main.(*builder).runOut(0xc08205eee0, 0xc0820bc930, 0x2f, 0xc082074e68, 0x7, 0x0, 0x0, 0x0, 0xc0821fd478, 0x1, ...)
        c:/go/src/cmd/go/build.go:1429 +0x350
main.gcToolchain.gc(0xc08205eee0, 0xc082061000, 0xc0820e1360, 0x47, 0xc0820e12c0, 0x4b, 0xc082105600, 0x4, 0x4, 0xc08219
a140, ...)
        c:/go/src/cmd/go/build.go:1667 +0xf53
main.(*gcToolchain).gc(0xaaf310, 0xc08205eee0, 0xc082061000, 0xc0820e1360, 0x47, 0xc0820e12c0, 0x4b, 0xc082105600, 0x4,
0x4, ...)
        <autogenerated>:3 +0x1a3
main.(*builder).build(0xc08205eee0, 0xc0821e29c0, 0x0, 0x0)
        c:/go/src/cmd/go/build.go:944 +0x282f
main.func┬╖005(0xc0821e29c0)
        c:/go/src/cmd/go/build.go:702 +0x3c0
main.func┬╖006()
        c:/go/src/cmd/go/build.go:759 +0x161
created by main.(*builder).do
        c:/go/src/cmd/go/build.go:765 +0x598

goroutine 8 [select, 129 minutes]:
main.func┬╖006()
        c:/go/src/cmd/go/build.go:749 +0x1da
created by main.(*builder).do
        c:/go/src/cmd/go/build.go:765 +0x598

goroutine 9 [select, 129 minutes]:
main.func┬╖006()
        c:/go/src/cmd/go/build.go:749 +0x1da
created by main.(*builder).do
        c:/go/src/cmd/go/build.go:765 +0x598

goroutine 10 [select, 129 minutes]:
main.func┬╖006()
        c:/go/src/cmd/go/build.go:749 +0x1da
created by main.(*builder).do
        c:/go/src/cmd/go/build.go:765 +0x598
```

**Comment by johnjelinek** [comment]
In my scenario, if the Box is about 4.5M, I can build just fine. If I add some images that bring it to about 7.3M then a memory leak happens and a build can't be produced.

**Comment by GeertJohan** [comment]
I'm not sure if this is a memory leak or just the compiler requiring a huge amount of memory to compile the huge source file that was created. In both cases: this is a compiler 'problem' and you might consider filing your issue to [golang/go](https://github.com/golang/go). Although it's not common for a source file to contain 33M bytes of source.. You might want to take a look at 'appending' your box. It's more suitable especially with larger boxes.

Closing this issue because, as far as I know, there is nothing I can do to fix this with embedding. Appending works fine in most cases.

**Comment by johnjelinek** [comment]
What option do I have if I don't want to ship a zip with my binary?

**Comment by GeertJohan** [comment]
The zip is appended directly to the binary file, you don't have to ship a separate zip file. Is this a problem for your product?

**Comment by johnjelinek** [comment]
I'm about to test and find out. I'll let you know.



—

**Comment by johnjelinek** [comment]
:'( now I'm getting #7. I'll try to cross-compile from linux.

**Comment by johnjelinek** [comment]
it works when cross-compiling. Thanks!

**Comment by GeertJohan** [comment]
Cool! Have fun :+1:
