### ISSUE TITLE
embedsyso supposed to work on Windos TM?

### ISSUE THREAD

**Issue by markfink** [GeertJohan/go.rice#79]
Hi, I am using embedsyso for quite a while now to embed the web frontend of my tool. So far it worked perfectly. 
Now I had to use my tool on Windows. Everything works fine besides the frontend.
I guess my question is: "is this supposed to work on windows?"

2nd thing I like to know is if I can do something - I mean beside the obvious fix it and submit a PR?

Yeah, I should probably mention two things... I already tried to get rid of the Unix path separator to avoid the Windows TM backslash extravagance. My attempt to resolve this was to write a specialized embedsyso boxer (https://github.com/finklabs/embedsyso). 

Here the console output of panic:
panic: could not locate box "../web"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0x808348, 0x6, 0x0)
        /home/mark/devel/gocode/src/github.com/GeertJohan/go.rice/box.go:110 +0x82
github.com/finklabs/GoGrinder/gogrinder.(*TestServer).Router(0x1274e180, 0x1274e180)
        /home/mark/devel/gocode/src/github.com/finklabs/GoGrinder/gogrinder/server.go:153 +0xae

**Comment by markfink** [comment]
just wanted to let you know that I really liked your tool and it worked fine for many weeks. I had to move on since I discovered that it does not work on Windows TM. I close the ticket since it is now irrelevant for me. I am now using https://github.com/elazarl/go-bindata-assetfs (not perfect either but works for now).
